### ISSUE TITLE
Margin note hover causes paragraph text reflow

### ISSUE THREAD

**Issue by kevinlin1** [amyjko/bookish#227]
When the `marginal-hovered` class is applied and the margin note is bolded, the increase space required for the bold text results in paragraph text reflow. Here's an example from the Critically Conscious Computing chapter on history.

![marginal-hovered](https://user-images.githubusercontent.com/1915715/130372911-06b81c7f-c0e0-4202-a2c2-7850659f10df.gif)

https://github.com/amyjko/peruse/blob/1dbcf94329a2a8a33aa6fe72edfa705f88bd4ebb/peruse.css#L569-L571

Usually, the line isn't too full so a line break won't be inserted; instead the rest of line will shift over a bit to the right. Two possible fixes come to mind.

1. Give each margin note sufficient width so that the bolded the margin note doesn't request more inline space.
2. Switch to a different style such as highlighting (for example) rather than bolding the margin note.

I'm using Chrome OS 92.

**Comment by amyjko** [comment]
Still an issue, adding to 1.0 milestone.

**Comment by amyjko** [comment]
This was resolved with this past year's Svelte rewrite.
