### ISSUE TITLE
Can't back out of write/login page

### ISSUE THREAD

**Issue by madbernard** [amyjko/bookish#325]
I'm using Chrome on Android. Steps to reproduce issue:

1. Go to "Write" page by clicking top nav
2. Since not logged in, get forwarded to login page
3. Click the Android back button

Expected: 
Go back to whatever page I was on before I clicked Write

Actual:
Flicker, but impossible to click quick enough to access my history

**Comment by amyjko** [comment]
Thanks for reporting! I've added this to my 1.0 milestone. I work on these each Saturday as a hobby, so expect progress to be slow but steady.

**Comment by amyjko** [comment]
Resolved by 8d01c53; needed to replace history state rather than append on login redirect.
