### ISSUE TITLE
Errors after uploading 3 or 4 images

### ISSUE THREAD

**Issue by timothyahaywood** [amyjko/bookish#333]
The system seems to freeze in "Saving" mode after 4 or 5 consecutive jpegs are uploaded. When it happened the first time I tried to refresh because it had been stuck for so long, but it kicked me out and some content wasn't saved.

**Comment by amyjko** [comment]
Thanks for reporting! I'll see if I can reproduce this.

**Comment by amyjko** [comment]
Unable to reproduce this; hopefully this is resolved after several other revisions to image uploading over the past year.
