### ISSUE TITLE
Unable to edit book browsing page

### ISSUE THREAD

**Issue by timothyahaywood** [amyjko/bookish#334]
It looks like there's some kind of code embedded in the text that keeps it from being editable. Also unable to navigate between chapters now.

**Comment by timothyahaywood** [comment]
Here's the url: https://bookish.press/write/NCW758OSUmq6G7JllX1J

The blurb above the chapter listing is not editable.

**Comment by amyjko** [comment]
This should be resolved now. (The image never appeared here, but I figured it out without it. Thanks!)

**Comment by timothyahaywood** [comment]
> This should be resolved now. (The image never appeared here, but I figured it out without it. Thanks!)

All systems go! All text has been re-input and everything is in its place. Thanks!
