### ISSUE TITLE
Escape characters in code block get double escaped and never unescaped

### ISSUE THREAD

**Issue by rbohrer** [amyjko/bookish#342]
To reproduce:

- Open the editor
- Type "return_type" (or any other text containing an underscore)
- Highlight that text and push the <> button that makes it into code
- Refresh the page
- Observe that the _ has turned into \\\_
- If you continue refreshing, the number of \ shall continue to grow without bound :D

Note: I tried it outside of a code block too and the bug did not occur there

Expected: invariance in the quantity of _ under page refresh

**Comment by rbohrer** [comment]
Added context: In large chapters, this gets quite problematic over time because the number of escape characters grows exponentially with the number of saves. After working on a chapter for a while I will go back and see whole pages of escape characters, or it will save and then scroll around because the save increased the number of lines of escape characters

**Comment by rbohrer** [comment]
(Sorry for rapid-fire comments, just been using the site a lot!)
The same issue also occurs in hyperlinks, for example when the URL contains a tilde ~

**Comment by amyjko** [comment]
This should be resolved now. It was a defect in escape character login in the serialization of code and links.
