### ISSUE TITLE
Unstable numbering in nested numbered lists

### ISSUE THREAD

**Issue by rbohrer** [amyjko/bookish#349]
Reproduction steps:

1. Create a new chapter and create a new numbered list
2. After entering the first element, hit newline to create a second item and hit the "indent list". This correctly converts "2" to "a"
3. Create a second and third element of the inner list, which are correctly labeled "b" and "c"
4. Press the "outdent list" button. The label "c" will convert to 3, which is incorrect, because it is now  the second element of the outer list and should read "2"

Priority/usage info: This comes up frequently when writing the exercises to each chapter. It breaks the most intuitive mode of creating nested lists. I suppose a workaround is possible but painful: create the full outer list before creating any inner lists.

**Comment by amyjko** [comment]
This was a CSS counter defect. I've migrated the CSS to more modern `list::marker` styling. While I was at it, I fixed the ordering of the indent/outdent buttons, which seemed backwards.
