### ISSUE TITLE
Editor unexpectedly snaps to Loading screen and stays there

### ISSUE THREAD

**Issue by rbohrer** [amyjko/bookish#351]
Today I was cleaning up text formatting in a chapter I've already written (Ch 3, Rust), mostly just adding "code" tags, and sometimes while I'm doing this, the "Loading" message will show up in place of the editor and it will get stuck that way until I refresh, after which it's fine. There are no messages in the dev console, but the following issues show up in the issues window of dev tools:
![image](https://github.com/amyjko/bookish/assets/1960801/e4e4c442-e492-4efc-af15-0c2f21fd515e)

My suspicion: this chapter has lots and lots of duplicate labels due to #346. I'm going to try removing them and see if that fixes it.

**Comment by rbohrer** [comment]
BTW: It's the longest chapter of the book (~1hr read time estimate) if that makes any difference

**Comment by amyjko** [comment]
Curious! I'll try some testing on the chapter. There may be an unhandled error lurking somewhere related to Firebase document size and write limits.

**Comment by rbohrer** [comment]
After further experimenting I think the problem was that I had the same
page open in two tabs at once

**Comment by amyjko** [comment]
Tagging #295 as possibly related.

**Comment by amyjko** [comment]
If this happens again when you're _not_ editing the same chapter in two separate tabs, do let me know. For now, I'll consider it related to #295, which is going to take a bit more work to handle.

**Comment by rbohrer** [comment]
Will do. Hasn't happened since, so I'm strongly suspecting the multiple tabs

**Comment by amyjko** [comment]
After extensive testing of #295, I believe this is now resolved.
