### ISSUE TITLE
Horizontal rule has much more spacing in read mode than in editor

### ISSUE THREAD

**Issue by rbohrer** [amyjko/bookish#356]
Example rule in editor: 
![image](https://github.com/amyjko/bookish/assets/1960801/25e63b3c-4dbd-41f1-a9d9-1817fd505501)
Same rule in reader:
![image](https://github.com/amyjko/bookish/assets/1960801/6e710b77-62cb-4c8a-8e9f-49d9c97411c7)

Setup: My usual: recent chrome on Win11 home
Theme: I use the "Bookish" theme. I played around with adding the following custom CSS and did not see a difference:
hr { margin: 10px 0 10px 0; }

Thoughts:
- The spacing in the editor is satisfactory for me. If we can get the same spacing in the reader, that would be perfect
- If it requires custom CSS, I'm happy to add custom CSS, but I would need some advice on which spacing values I need to customize

**Comment by amyjko** [comment]
Found the culprit: it only looked nice in the editor because of some deprecated global styling that was masking the bad styling applied to rules. I've removed the deprecated global styling and made the bad styling on rules good.
