### ISSUE TITLE
Alphabetization in references list IDs

### ISSUE THREAD

**Issue by amyjko** [amyjko/bookish#369]
## Expected behavior

References should be alphabetized.

## Actual behavior

Within the scope of the reference IDs that serve as the ordering basis for the list, capital letters (A-Z) all are treated as coming before lowercase letters (a-z). So, in this screenshotted example, any tag that starts with a capital letter ("TEST") will be placed before any tags that start with a lowercase letter ("acmCode").

Probably related to ASCII comparison. Workaround is to be consistent with caps at the beginning of the ID.

## Screenshots

![](https://files.slack.com/files-pri/TTZDY941G-F06JLDB0X97/screenshot_2024-02-10_at_2.06.42_pm.png)

**Comment by orcmid** [comment]
Yes, I just grabbed a well-indexed book and saw that all the alphabetic index items have initial capitals (except that `al-Khwārizmī` comes before `ALF` and CJK and (Sanskrit?) names are given romanized first, sometimes in spoken order rather than "last-name" first.
